/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import java.awt.CardLayout;


/**
 *
 * @author sidik ansari
 */
public class PilihGambarButton extends javax.swing.JFrame {

    /**
     * Creates new form PilihGambarButton
     */
    public PilihGambarButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        shopee = new javax.swing.JButton();
        tokopedia = new javax.swing.JButton();
        lazada = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        imagePanel = new javax.swing.JPanel();
        shopeeLB = new javax.swing.JLabel();
        tokopediaLB = new javax.swing.JLabel();
        lazadaLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        shopee.setText("Shopee");
        shopee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shopeeActionPerformed(evt);
            }
        });
        buttonPanel.add(shopee);

        tokopedia.setText("Tokopedia");
        tokopedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tokopediaActionPerformed(evt);
            }
        });
        buttonPanel.add(tokopedia);

        lazada.setText("Lazada");
        lazada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lazadaActionPerformed(evt);
            }
        });
        buttonPanel.add(lazada);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        buttonPanel.add(exit);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        imagePanel.setLayout(new java.awt.CardLayout());

        shopeeLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/logo-shopee.jpg"))); // NOI18N
        imagePanel.add(shopeeLB, "0");
        shopeeLB.getAccessibleContext().setAccessibleName("");

        tokopediaLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/logo-tokopedia.png"))); // NOI18N
        imagePanel.add(tokopediaLB, "1");
        tokopediaLB.getAccessibleContext().setAccessibleName("");

        lazadaLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/logo-lazada.png"))); // NOI18N
        imagePanel.add(lazadaLB, "2");
        lazadaLB.getAccessibleContext().setAccessibleName("");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void shopeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shopeeActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel, "0");
    }//GEN-LAST:event_shopeeActionPerformed

    private void tokopediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tokopediaActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel, "1");
    }//GEN-LAST:event_tokopediaActionPerformed

    private void lazadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lazadaActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel, "2");
    }//GEN-LAST:event_lazadaActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihGambarButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton exit;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JButton lazada;
    private javax.swing.JLabel lazadaLB;
    private javax.swing.JButton shopee;
    private javax.swing.JLabel shopeeLB;
    private javax.swing.JButton tokopedia;
    private javax.swing.JLabel tokopediaLB;
    // End of variables declaration//GEN-END:variables
}
